#!/usr/bin/env python3

#   @orcuntuna
#   lampp helper script

import sys
import os
import os.path
import sys

lampp_path = "/opt/lampp/"

args = len(sys.argv)

if(args > 1):

    komut = sys.argv[1]

    if(komut == "start"):
        os.system("sudo " + lampp_path + "lampp start") #start
    elif(komut == "stop"):
        os.system("sudo " + lampp_path + "lampp stop") #stop
    elif(komut == "gui"):
        dosya1 = lampp_path + "manager-linux-x64.run" #64 bit
        dosya2 = lampp_path + "manager-linux.run" #32 bit
        if(os.path.isfile(dosya1)):
            os.system("sudo chmod +x " + dosya1) #64 bit chmod
            os.system("sudo " + dosya1) #64 bit open
        elif(os.path.isfile(dosya2)):
            os.system("sudo chmod +x " + dosya2) #32 bit chmod
            os.system("sudo " + dosya2) #32 bit open
        else:
            print("GUI can't found")
    elif(komut == "--help"):
        print("""
        cd $(xampp)  :   jump lampp htdocs directory
        xampp start  :   start all services
        xampp stop   :   stop all services
        xampp gui    :   run lampp gui application
        """) #help
    else:
        print("wrong parameter")
else:
    print(lampp_path + "htdocs/")